### PR TITLE
Adding the google crawler

### PR DESCRIPTION
**Pull request by AggarwalAditya**
The script uses 2 python modules:
- readibility api  (install using 'pip install readibility-api')
- google-api-python-client (install using 'pip install google-api-python-client')

Also please register your project on the google console and readibility api's to generate the api keys.

Google search CANNOT be crawled therefore I have used the custom search api.

### CODE REVIEW

**Comment by AggarwalAditya** [comment]
If you want , I can give you the fully running code along with my API keys :D.

**Comment by adishjain** [comment]
That's not really a problem. 
We're basically trying to provide custom code here in different languages. 
More so in a form of ready to use template. 
So you can just mention the steps or provide whatever is necessary is totally upon you. 
Thanks

**Comment by AggarwalAditya** [comment]
To run the code, you'll need to install 2 python modules:
- readability ----> in terminal type "pip install readibility-api"
  -google-api-python-client ---->'pip install google-api-python-client

Also generate custom search API keys through the Google API dashboard.
Similarly for readiblity API ,generate keys by registering yourself in the readiblity dashboard.

Fill up the keys in the space provided in the code and you are good to go.

I hope this code helps you ...

**Comment by adishjain** [comment]
Cool. I'll merge this one.

**Pull request merged**
